[package]
name = "kafka-delta-ingest"
version = "0.1.0"
authors = ["R. Tyler Croy <rtyler@scribd.com>", "Christian Williams <christianw@scribd.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
bytes = "~1.0"
cfg-if = "1"
chrono = "0"
clap = { version = ">=3.0.0-beta.2,<4", features = ["color"] }
crossbeam = { version = "0" }
env_logger = "0"
futures = "0.3"
log = "0"
rdkafka = "~0.25.0"
regex = "1"
rusoto_core = { version = "0.46" }
rusoto_s3 = { version = "0.46" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1", features = ["fs", "macros", "rt", "io-util"] }
tokio-stream = { version = "0", features = ["fs"] }
uuid = { version = "0.8", features = ["serde", "v4"] }

arrow  = { git = "https://github.com/apache/arrow.git", rev = "05b36567bd8216bec71b796fe3bb6811c71abbec" }
deltalake = { git = "https://github.com/delta-io/delta-rs.git", rev = "4170d34c90da21ee406c0aa0a15dc5bf09eba011" }
parquet = { git = "https://github.com/apache/arrow.git", rev = "05b36567bd8216bec71b796fe3bb6811c71abbec" }

[dev-dependencies]
utime = "0.3"
serial_test = "*"