[package]
name = "kafka-delta-ingest"
version = "0.1.0"
authors = ["R. Tyler Croy <rtyler@scribd.com>", "Christian Williams <christianw@scribd.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
